- platform: template
  sensors:
    windnaam:
      value_template: >
        {% set direction = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW','N'] %}
        {% set degree = states('sensor.windrichting_azimut')|float %}
        {{ direction[((degree+11.25)/22.5)|int] }}
